<?php

namespace Lo\EpiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategorieArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieArticleRepository extends EntityRepository
{
}
