<?php

namespace Epi\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function findNews()
  {
    // Méthode équivalente, mais plus longue :
    $queryBuilder = $this->createQueryBuilder('N');
	
	$queryBuilder->where('N.publication = 1');
 
    $queryBuilder->orderBy('N.date', 'DESC');
 
    // On récupère la Query à partir du QueryBuilder
    $query = $queryBuilder->getQuery();
 
    // On récupère les résultats à partir de la Query
    $resultats = $query->getResult();
 
    // On retourne ces résultats
    return $resultats;
  }
}
