<?php

namespace Epi\BoutiqueBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{

	public function myFindByNom($nom)
    {
    $qb = $this->createQueryBuilder('p');
    $qb->where("p.nom LIKE '%:nom%'")
       ->setParameter('nom', $nom);
    return $qb->getQuery()
              ->getResult();
    }
}
