parameters:
#    epi_boutique.example.class: Epi\BoutiqueBundle\Example

services:
#    epi_boutique.example:
#        class: %epi_boutique.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
