parameters:
#    epi_admin.example.class: Epi\AdminBundle\Example

services:
#    epi_admin.example:
#        class: %epi_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
